name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 537124976047.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push images
        run: |
          docker build -t $ECR_REGISTRY/stegano-api:latest .
          docker push $ECR_REGISTRY/stegano-api:latest

          docker build --build-arg VITE_API_BASE=http://3.88.139.96:8000 -t $ECR_REGISTRY/stegano-dashboard:latest ./3_Web_Dashboard/react-dashboard
          docker push $ECR_REGISTRY/stegano-dashboard:latest

          docker build --build-arg VITE_API_BASE=http://3.88.139.96:8000 -t $ECR_REGISTRY/stegano-mail:latest ./3_Web_Dashboard/react-mail
          docker push $ECR_REGISTRY/stegano-mail:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command_timeout: 30m
          script: |
            cd ~/stegano-gateway
            git fetch origin
            git reset --hard origin/main
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 537124976047.dkr.ecr.us-east-1.amazonaws.com
            bash deploy.sh